[package]
name = "humctrl"
version = "0.1.0"
authors = ["Mitchell Bruckner <mbruckner807@gmail.com>"]


[[bin]]
name = "humctrl"

[[bin]]
name = "dft"

[dependencies]
portaudio="0.7.0"
hyper="0.9.10"
rand="0.3"
